name: dispatch-ci.yml

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    env:
      UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
      UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
      UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
      - name: Cache Library
        uses: actions/cache@v4
        with:
          path: src/Library
          key: Library-lint-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: Library-lint-

      - uses: game-ci/unity-builder@v4
        with:
          projectPath: src
          unityVersion: 2022.3.18f1
          targetPlatform: StandaloneWindows64
