name: unified-check-ci.yml

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened, edited, ready_for_review]
  push:
    paths:
      - 'src/Assets/Scripts/**'
      - '**/*.cs'
    branches:
      - main
      - develop
      - 'release/*'
    tags:
      - 'v*'

jobs:
  determine-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check for script or .cs file changes
        id: check_scripts
        run: |
          FILES_CHANGED=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -E 'src/Assets/Scripts/|\.cs$' | wc -l)
          if [ "$FILES_CHANGED" -gt 0 ]; then
            echo "SCRIPT_CHANGED=true" >> $GITHUB_ENV
          else
            echo "SCRIPT_CHANGED=false" >> $GITHUB_ENV
          fi
        shell: bash

  code-check:
    runs-on: ubuntu-latest
    needs: determine-changes
    if: env.SCRIPT_CHANGED == 'true'
    env:
      UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
      UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
      UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}  # to check out the actual pull request commit, not the merge commit
          fetch-depth: 0  # a full history is required for pull request analysis
      - name: Cache Library
        uses: actions/cache@v4
        with:
          path: src/Library
          key: Library-lint-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: Library-lint-

      - uses: game-ci/unity-builder@v4
        with:
          projectPath: src
          unityVersion: auto
          buildMethod: Packages.Rider.Editor.RiderScriptEditor.SyncSolution
          targetPlatform: StandaloneWindows64

  test:
    runs-on: ubuntu-latest
    if: env.SCRIPT_CHANGED == 'true'
    env:
      UNITY_LICENSE: ${{ secrets.UNITY_V2022X_LICENSE }}
      UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
      UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: Restore Cache
        uses: actions/cache@v4
        with:
          path: src/Library
          key: Library-lint-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: Library-lint-
      - uses: game-ci/unity-test-runner@v4
        id: tests
        with:
          projectPath: src
          unityVersion: auto
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          testMode: All
      - uses: actions/upload-artifact@v4
        name: Upload Test artifacts
        if: always()
        with:
          name: test-artifacts
          path: ${{ steps.tests.outputs.artifactsPath }}

  convert-to-markdown:
    runs-on: ubuntu-latest
    needs: test
    if: env.SCRIPT_CHANGED == 'true'
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      PR_NUMBER: ${{ github.event.pull_request.number }}
      PR_URL: ${{ github.event.pull_request.html_url }}
      PR_TITLE: ${{ github.event.pull_request.title }}
      PR_BODY: ${{ github.event.pull_request.body }}
      PR_CREATED_AT: ${{ github.event.pull_request.created_at }}
      PR_HEAD_REF: ${{ github.event.pull_request.head.ref }}
      PR_BASE_REF: ${{ github.event.pull_request.base.ref }}
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: Download Test Artifacts
        uses: actions/download-artifact@v4
        with:
          name: test-artifacts
          path: artifacts  # ダウンロードするパス

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
          bundler-cache: true
  
      - name: Install Ruby Dependencies
        run: |
          gem install bundler
          bundle install
        working-directory: scripts
  
      - name: Convert XML to Markdown
        run: |
          ruby scripts/test_result_convert_md.rb artifacts output.md
      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request' && hashFiles('output.md') != ''
        with:
          recreate: true
          header: "Ready to Merge"
          path: ./output.md

  comment-on-pr:
    runs-on: ubuntu-latest
    needs: determine-changes
    if: env.SCRIPT_CHANGED == 'false'
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - name: Add Merge Comment
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          recreate: true
          hide_and_recreate: true
          header: "Ready to Merge"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          message: |
            ### ✅ Ready to Merge
            
            This pull request does not include any changes in `src/Assets/Scripts/**` or `*.cs` files.
            It is safe to merge without further code review.
            
            #### Pull Request Summary
            
            - **Title:** [${{ github.event.pull_request.title }}](${{ github.event.pull_request.html_url }})
            - **Author:** @${{ github.actor }}
            - **Created at:** ${{ github.event.pull_request.created_at }}
            - **Base Branch:** `${{ github.event.pull_request.base.ref }}`
            - **Head Branch:** `${{ github.event.pull_request.head.ref }}`
            
            <details>
            <summary>Click to expand PR details</summary>
            
            - **PR Number:** #${{ github.event.pull_request.number }}
            - **Body:**
                ${{ github.event.pull_request.body }}
            
            </details>
            
            ---
            
            ### Next Steps
            
            1. Ensure all checks have passed.
            2. Verify that no additional changes are needed.
            3. [Merge this pull request](${{ github.event.pull_request.html_url }}) when ready.
            
            If you have any questions or need further clarification, please reach out to the author or reviewers.